### ISSUE TITLE
InvalidRepositoryError ketika migrasi

### ISSUE THREAD

**Issue by iromli** [femmerling/nembok#1]
Error traceback:

```
Traceback (most recent call last):
  File "./box.py", line 545, in <module>
    db_migrate()
  File "./box.py", line 59, in db_migrate
    migration = SQLALCHEMY_MIGRATE_REPO + '/versions/%03d_migration.py' % (api.db_version(SQLALCHEMY_DATABASE_URI, SQLALCHEMY_MIGRATE_REPO) + 1)
  File "<string>", line 2, in db_version
  File "/opt/contrib/nembok/box/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 159, in with_engine
    return f(*a, **kw)
  File "/opt/contrib/nembok/box/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 148, in db_version
    schema = ControlledSchema(engine, repository)
  File "/opt/contrib/nembok/box/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 28, in __init__
    repository = Repository(repository)
  File "/opt/contrib/nembok/box/local/lib/python2.7/site-packages/migrate/versioning/repository.py", line 77, in __init__
    self.verify(path)
  File "/opt/contrib/nembok/box/local/lib/python2.7/site-packages/migrate/versioning/repository.py", line 98, in verify
    raise exceptions.InvalidRepositoryError(path)
migrate.exceptions.InvalidRepositoryError: /opt/contrib/nembok/db_repository
```

Mungkin kita harus include file migration-nya?

**Comment by femmerling** [comment]
run ./box.py -c to create the db. delete the db_repository folder if it existed before you run the command

**Comment by iromli** [comment]
ok, it works :+1:

**Comment by ghost** [comment]
Hi, my script not running.

/db_migrate.py
/home/helias/Documents/venviu/local/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Traceback (most recent call last):
  File "./db_migrate.py", line 7, in <module>
    v = api.db_version(SQLALCHEMY_DATABASE_URI, SQLALCHEMY_MIGRATE_REPO)
  File "<decorator-gen-6>", line 2, in db_version
  File "/home/helias/Documents/venviu/local/lib/python2.7/site-packages/migrate/versioning/util/**init**.py", line 160, in with_engine
    return f(_a, *_kw)
  File "/home/helias/Documents/venviu/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 148, in db_version
    schema = ControlledSchema(engine, repository)
  File "/home/helias/Documents/venviu/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 29, in **init**
    repository = Repository(repository)
  File "/home/helias/Documents/venviu/local/lib/python2.7/site-packages/migrate/versioning/repository.py", line 77, in **init**
    self.verify(path)
  File "/home/helias/Documents/venviu/local/lib/python2.7/site-packages/migrate/versioning/repository.py", line 98, in verify
    raise exceptions.InvalidRepositoryError(path)
migrate.exceptions.InvalidRepositoryError: /home/helias/Documents/venviu/microb/db_repository

Versions:
Flask-SQLAlchemy==2.1
Flask-WhooshAlchemy==0.56
sqlalchemy-migrate==0.10.0
SQLAlchemy==1.0.12

Help me! :)
